apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      securityContext:
        runAsUser: 1000  # Use non-root user for running the container
        runAsGroup: 3000
        fsGroup: 2000
      containers:
      - name: flask-app
        image: example/flask-app:v1.0.0
        ports:
        - containerPort: 8080
        securityContext:
          allowPrivilegeEscalation: false  # Prevent privilege escalation
          readOnlyRootFilesystem: true  # Set read-only root filesystem
        resources:
          requests:
            cpu: "100m"  # Set CPU request
            memory: "128Mi"  # Set memory request
          limits:
            cpu: "200m"  # Set CPU limit
            memory: "256Mi"  # Set memory limit
