apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask-app
  ports:
  - protocol: TCP
    port: 80  # External port to access the service
    targetPort: 8080  # Port your Flask application is listening on
  type: LoadBalancer  # Use LoadBalancer for external access (you can change this to `NodePort` if using a local cluster)
